/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Tomás de Aquino Domínguez Gómez
 * Created: 19-dic-2020
 */
DROP TABLE RELACION;
DROP TABLE PERSONA;
DROP TABLE SESION;
DROP TABLE PELICULA;

CREATE TABLE PELICULA (
    ID          INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    TITULO      VARCHAR(25) NOT NULL,
    FECHA_START DATE NOT NULL,
    FECHA_END   DATE NOT NULL,

    CONSTRAINT ID_PELICULA_PK PRIMARY KEY (ID)
);


CREATE TABLE SESION (
    ID          INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODIGO      CHAR(4) NOT NULL,
    DIA_HORA    TIMESTAMP NOT NULL,
    PELICULA    INTEGER NOT NULL,

    CONSTRAINT ID_SESION_PK PRIMARY KEY (ID),
    CONSTRAINT PEL_SESION_FK FOREIGN KEY (PELICULA) REFERENCES PELICULA(ID)
);

CREATE TABLE PERSONA (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE      VARCHAR(25) NOT NULL,
    APELLIDOS   VARCHAR(45) NOT NULL,
    TELEFONO    CHAR(9) NOT NULL,
    REGISTRO    TIMESTAMP,

    CONSTRAINT ID_PERSONA_PK PRIMARY KEY (ID)
);

CREATE TABLE RELACION (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    PELICULA_ID INTEGER NOT NULL,
    SESION_ID INTEGER NOT NULL,
    PERSONA_ID INTEGER NOT NULL,

    CONSTRAINT ID_RELACION_PK PRIMARY KEY (ID),
    CONSTRAINT PEL_RELACION_FK FOREIGN KEY (PELICULA_ID) REFERENCES PELICULA (ID),
    CONSTRAINT SES_RELACION_FK FOREIGN KEY (SESION_ID) REFERENCES SESION (ID), 
    CONSTRAINT PER_RELACION_FK FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA (ID)
);